### ISSUE TITLE
[Enhancement] WriteFully for a dynamic String.

### ISSUE THREAD

**Issue by Electrolyt** [ssilverman/QNEthernet#2]
Hi Silverman,

you made a really impressive ethernet library for the teensy 4.1.
It's fantastic. The library is much more stable like old once for the Teensy 3.x.
Is it possible to add a new function for a dynamic string 
to transfer them completely with the WriteFully-command?
I will use it for my web-server.
Example:

WebClient.writeFully("<s40>");
WebClient.print(String (IO.sDC_Current[1]));
WebClient.writeFully("</s40>\r\n");

Best greetings

**Comment by ssilverman** [comment]
Thank you.

I’m not completely certain what you’re asking for. There’s already functions for transferring both bytes and chars. What is `IO.sDC_Current[1]`?

**Comment by ssilverman** [comment]
My intent for the `writeFully()` functions was to match the `write()` functions. It is my preference not to provide too many convenience functions because it’s often straightforward to convert to arguments needed by one of the existing forms, for example, `String::c_str()`.

What happens if you try this:
```c++
WebClient.print(String(IO.sDC_Current[1]).c_str());
```

I may change my mind in the future, but I first want to see the prevalence of needs for `writeFully(String)`.

**Comment by Electrolyt** [comment]
oh, i'am sorry for my incomplete description. 
It is only a variable like integer that will converted into a string.
my meaning: 

WebClient.writeFully("");
WebClient.print(String (intVar));
WebClient.writeFully("\r\n");

About of the String::c_str(). I dind`t know about that. This did the trick. 
I will use:

WebClient.writeFully((String (intVar)).c_str());
I will rewrite my sketch to test them.

Thanks...

**Comment by ssilverman** [comment]
I’m curious, why are you writing an empty string in the first line?

**Comment by Electrolyt** [comment]
WebClient.writeFully(""); -> this isn`t realy in my sketch. i modified this only for the posting.
i know the command isn`t necessary.

**Comment by ssilverman** [comment]
I’m sorry, I mistyped my comment above. I meant this:

```c++
WebClient.writeFully(String(IO.sDC_Current[1]).c_str());
```

**Comment by Electrolyt** [comment]
Yes, we mean both the same.
Thank you. Can i ask you in the future again two things.
I haven`t now time for that.
I will leave this issue open, just for communication okey ?

**Comment by ssilverman** [comment]
If it’s a different subject from “writeFully(String)”, I’d prefer to use a different issue. Maybe the questions can help others, but I think categorization is important.
