### ISSUE TITLE
System hang when connecting to client that doesn't exist.

### ISSUE THREAD

**Issue by videojedi** [ssilverman/QNEthernet#5]
When trying to connect to a host that doesn't exist, I get this error. I'm using QNethernet in conjunction with Websockets and EthernetWebserver.

Assertion "tcp_input: pcb->next != pcb (before cache)" failed at line 269 in C:\Users\admin\Documents\Arduino\libraries\QNEthernet\src\lwip\tcp_in.c

(as discussed here [https://github.com/ssilverman/QNEthernet/discussions/4] )

**Comment by ssilverman** [comment]
Thank you. Did you mean to close this?

**Comment by videojedi** [comment]
sorry, re-opened properly from the discussion......
