### ISSUE TITLE
Disabling DNS and STATS

### ISSUE THREAD

**Issue by Stevenlawrencehoriba** [ssilverman/QNEthernet#58]
I have tried to disable DNS and STATS, using -DLWIP_MDNS_RESPONDER=0 and -DLWIP_STATS=0. Whats the best way to disbale these features so we can gain a bit more heap space.

**Comment by ssilverman** [comment]
Just to clarify, you want more heap for malloc and dynamic memory? If you define QNETHERNET_BUFFERS_IN_RAM1, that will put the internal buffers in RAM1 and not RAM2/DMAMEM, saving about 15k of heap, but moving them to RAM1.

A few notes:
1. Setting LWIP_MDNS_RESPONDER=0 disables the mDNS responder, not DNS support.
2. LWIP_STATS is disabled by default in_lwipopts_.

**Comment by ssilverman** [comment]
Is this still an issue for you?

**Comment by ssilverman** [comment]
Closing for now; please reopen if you have more questions.
