### ISSUE TITLE
`client.connect` should return true or false

### ISSUE THREAD

**Issue by JAndrassy** [ssilverman/QNEthernet#74]
Hello. 
the Arduino Ethernet library has client.connect() documentation fixed.
https://www.arduino.cc/reference/en/libraries/ethernet/client.connect/
> Returns true if the connection succeeds, false if not.

please consider aligning the `client.connect` method in your library with other Arduino networking libraries

**Comment by ssilverman** [comment]
That’s because I filed a bug report on the site last week. :)

It’ll be updated to match the new site contents.

**Comment by JAndrassy** [comment]
yes maybe that was the cause for my PR https://github.com/arduino-libraries/Ethernet/pull/240 to be finally merged

**Comment by ssilverman** [comment]
Teamwork!
