### ISSUE TITLE
documentation:  MDNS.hostname() returns a String, rather than c_string

### ISSUE THREAD

**Issue by palmerr23** [ssilverman/QNEthernet#85]
A simple addition to the documentation could avoid confusion:

cStrings (char *) tend to be default elsewhere [e.g. MDNS.begin(const char *hostname)], however MDNS.hostname() returns a String [String hostname( )].

Making that clear in the readme would be helpful - even by just capitalising the S in `'and an empty String otherwise'`!

**Comment by ssilverman** [comment]
Thanks for the comment. It so happens that I’ve already changed the hostname() calls over the weekend, coincidentally.

On another note, the reason it returned a String was that it separates user access from any internal contents. The String object is a self-contained group of characters that owns its own memory.
