### ISSUE TITLE
Any plan to support mbedtls 3.x?

### ISSUE THREAD

**Issue by cabbi** [ssilverman/QNEthernet#86]
I'm wondering if QNEthernet library is going to support mbedtls version 3.x.
Would it be hard by following this guide? [Migrating from Mbed TLS 2.x to Mbed TLS 3.0](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/3.0-migration-guide.md)

**Comment by ssilverman** [comment]
I would love to add support for Mbed TLS 3.x. The lwIP way is to write an "altcp" adapter layer that decorates the regular TCP layer. Mbed TLS 3.x does things a little differently than 2.x, so a new adapter layer needs to be written. If and when I get a chance to look at it, I will, but that all depends on my availability. Ideally, someone who uses lwIP can do this, or maybe the lwIP community will come up with something at some point.

**Comment by ssilverman** [comment]
I just noticed the link (note to readers: it was added after the original comment). Thanks for that; I'll have a look.

**Comment by ssilverman** [comment]
Closing this for now with "I might get to it when I might get to it."
